name: _tf-plan

on:
  workflow_call:
    inputs: 
      environment:
        required: true
        type: string
      workspace:
        type: string
        default: 'default'

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          add_github_comment: false
          workspace: ${{ inputs.workspace }}
          var_file: |
            ${{ inputs.workspace }}.tfvars

  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: ${{ inputs.environment }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          auto_approve: true
          workspace: ${{ inputs.workspace }}
          var_file: |
            ${{ inputs.workspace }}.tfvars
