name: Destroy

concurrency: terraform-lock

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of the GitHub Environment'
        type: environment
        required: true
      workspace:
        description: 'Name of the workspace to view outputs'
        type: string
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest
    name: Destroy
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Destroy
        id: outputs
        uses: dflook/terraform-destroy@v1
        with:
          workspace: ${{ inputs.workspace }}
          var_file: |
            ./vars/${{ inputs.workspace }}.tfvars
