name: Detect Drift

on:
  schedule:
    - cron: 0 6 * * *

  workflow_dispatch:

jobs:
  staging:
    uses: ./.github/workflows/_tf-detect-drift.yaml
    with:
      workspace: staging

  production:
    uses: ./.github/workflows/_tf-detect-drift.yaml
    with:
      workspace: production
