name: New Workspace

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Name of the workspace to create'
        type: string
        required: true

jobs:
  new_workspace:
    runs-on: ubuntu-latest
    name: New Workspace
    steps:
      - uses: actions/checkout@v3

      - name: New Workspace
        uses: dflook/terraform-new-workspace@v1
        with:
          workspace: ${{ inputs.workspace }}
