name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: terraform plan
        id: plan
        uses: dflook/terraform-plan@v1

      - name: Plan Output
        run: echo "${{ steps.plan.outputs.json_plan_path }}"
