name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    uses: ./.github/workflows/_tf-plan.yaml
    with:
      environment: staging
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  apply:
    runs-on: ubuntu-latest
    environment: staging
    needs: plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      # - name: terraform plan
      #   id: plan
      #   uses: dflook/terraform-plan@v1

      # - name: Plan Output
      #   run: echo "${{ steps.plan.outputs.json_plan_path }}"

      # - name: terraform plan
      #   id: plan
      #   uses: dflook/terraform-plan@v1

      # - name: terraform apply
      #   id: apply
      #   uses: dflook/terraform-apply@v1
