name: Release

concurrency: terraform-lock

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:

  staging:
    uses: ./.github/workflows/_tf-release.yaml
    with:
      environment: staging
      workspace: staging

  production:
    needs: staging
    uses: ./.github/workflows/_tf-release.yaml
    with:
      environment: production
      workspace: production
