name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  staging:
    uses: ./.github/workflows/_tf-apply.yaml
    with:
      environment: staging
      workspace: staging
      var_file: |
        staging.tfvars

  production:
    needs: staging
    uses: ./.github/workflows/_tf-apply.yaml
    with:
      environment: production
      workspace: production
      var_file: |
        production.tfvars
